[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork --nopidfile
priority=1
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:sesman]
command=/usr/sbin/xrdp-sesman --nodaemon
priority=10
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:xrdp]
command=/usr/sbin/xrdp --nodaemon
priority=20
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:scalert]
command=/home/sysop/seiscomp/bin/seiscomp exec scalert
user=sysop
environment=HOME="/home/sysop",USER="sysop",LOGNAME="sysop",SEISCOMP_ROOT="/home/sysop/seiscomp",PATH="/home/sysop/seiscomp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",LD_LIBRARY_PATH="/home/sysop/seiscomp/lib",PYTHONPATH="/home/sysop/seiscomp/lib/python",QT_QPA_PLATFORM="xcb"
priority=30
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
